# Generated by Django 4.2.23 on 2025-08-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tertiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tertiary_building', models.CharField(choices=[('EM', 'Empty'), ('AH', 'Alehouse'), ('AR', 'Arena'), ('AT', 'Artisans'), ('BL', 'Bullaun'), ('CC', 'Church Crafts'), ('CH', 'Church'), ('CM', 'Craft Merchant'), ('ES', 'Estate'), ('FG', 'Forge'), ('GA', 'Garrison'), ('GR', 'Granary'), ('HP', 'Herring Port'), ('LB', 'Library'), ('MF', 'Market Fair'), ('MR', 'Merchant'), ('MI', 'Mill'), ('MT', 'Mint'), ('PT', 'Port'), ('RT', 'Round Tower'), ('SC', 'Scribes'), ('TA', 'Tanner'), ('TH', 'Tithe Hall'), ('TL', 'Tools'), ('TP', 'Trade Port'), ('VP', 'Viking Port'), ('WH', 'Warehouse'), ('WK', 'Workshop')], default='EM', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='tertiary_building_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_building_1_of', to='planner.tertiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tertiary_building_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_building_2_of', to='planner.tertiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tertiary_building_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_building_3_of', to='planner.tertiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tertiary_building_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_building_4_of', to='planner.tertiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tertiary_building_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_building_5_of', to='planner.tertiary'),
            preserve_default=False,
        ),
    ]
