# Generated by Django 4.2.23 on 2025-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_tertiary_plan_tertiary_building_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertiary',
            name='tertiary_building',
            field=models.CharField(choices=[('EM', 'Empty'), ('AH', 'Alehouse'), ('AR', 'Arena'), ('AT', 'Artisans'), ('BL', 'Bullaun'), ('CC', 'Church Crafts'), ('CH', 'Church'), ('CM', 'Craft Merchant'), ('ES', 'Estate'), ('FG', 'Forge'), ('GA', 'Garrison'), ('GR', 'Granary'), ('HP', 'Herring Port'), ('LB', 'Library'), ('MF', 'Market Fair'), ('MR', 'Merchant'), ('MI', 'Mill'), ('MT', 'Mint'), ('MH', 'Moot Hill'), ('PT', 'Port'), ('RT', 'Round Tower'), ('SC', 'Scribes'), ('TA', 'Tanner'), ('TH', 'Tithe Hall'), ('TL', 'Tools'), ('TP', 'Trade Port'), ('VP', 'Viking Port'), ('WH', 'Warehouse'), ('WK', 'Workshop')], default='EM', max_length=2),
        ),
    ]
